ENTRY(_load)
OUTPUT_FORMAT(binary)
/* OUTPUT_FORMAT(elf32-i386) */
/* STARTUP(build/a_kernel-entry.asm.o) */

SECTIONS
{
  . = 0x9000; /*2M;*/
  .text BLOCK(4K) : ALIGN(4K)
	{
		*(.multiboot)
		*(.text)
	}

	/* Read-only data. */
	.rodata BLOCK(4K) : ALIGN(4K)
	{
		*(.rodata)
	}

	/* Read-write data (initialized) */
	.data BLOCK(4K) : ALIGN(4K)
	{
		*(.data)
	}

	/* Read-write data (uninitialized) and stack */
	.bss BLOCK(4K) : ALIGN(4K)
	{
		*(COMMON)
		*(.bss)
	}
}