#include <multiboot.h>
#include <memory.h>
#include <types.h>
#include <printf.h>
#include <utils.h>

#define KERNEL_START    0x00200000
#define SKETCH_PAGE     0xc07ff000

// Assembly magic to obtain the linker's final size for all of the kernel text/[un]initialized data
extern uint32_t get_kernel_size();
extern uint32_t read_cr3();
extern void     swap_page_dir(void* addr);

// This is the kernel page directory, and is the 
extern uint32_t kernel_page_dir[1024];
extern uint32_t data_page_table[1024];

// The starting (physical) address of the memory pool
static size_t mem_pool_start    = 0;
// How big the memory pool is
static size_t mem_pool_len      = 0;
// How much of the memory pool has been used
static size_t mem_pool_used     = 0;

// The pointer to the current page directory
static size_t* current_page_dir;

// The base of the memory used for kmalloc()
static void*    ds_base;
// The end of the memory used for kmalloc()
static void*    ds_end;
// The "fake" amount of memory used by kmalloc()
static size_t   ds_used;
// The real amount of memory (this is always page aligned) used by kmalloc()
static size_t   ds_len;

// Cause a TLB flush on the current page directory.
// This is supposedly slow, though I'm not sure.
void flush_tlb() {
    __asm__ volatile("push %eax\nmov %cr3, %eax\nmov %eax, %cr3\npop %eax\n");
}

static inline void invalidate_page(size_t addr) {
    // fuck you, gnu inline assembly!
    // __asm__ volatile("invplg (%0)" :: "m" (addr) : "memory");
    flush_tlb();
}

// Swap the current page directory; pagedir is a virtual address
void swap_pagedir(void* pagedir) {
    void* v = virt_to_phys(pagedir);
    swap_page_dir(v);
    current_page_dir = pagedir;
}

// This was generated by chatgpt; thanks chatgpt
void* separate_and_pick_larger_three_sections(void* block, size_t total_size, size_t address1, size_t address2) {
    // Validate that the split addresses are within bounds
    if (address1 >= total_size || address2 >= total_size || address1 >= address2) {
        kpanic("Invalid address (0x%08X, 0x%08X)", address1, address2);
    }

    // Define the three sections
    void* first_section = block;
    void* second_section = (char*)block + address1;
    void* third_section = (char*)block + address2;

    size_t first_section_size = address1;
    size_t second_section_size = address2 - address1;
    size_t third_section_size = total_size - address2;

    // Pick the largest section
    void* larger_section = first_section;
    size_t larger_size = first_section_size;

    if (second_section_size > larger_size) {
        larger_section = second_section;
        larger_size = second_section_size;
    }

    if (third_section_size > larger_size) {
        larger_section = third_section;
        larger_size = third_section_size;
    }

    // Return the larger section
    return larger_section;
}

void mem_init(multiboot_info_t *mbd) {
    printf("Kernel size: %u pages (%u bytes)", (get_kernel_size())/4096+1, get_kernel_size());

    for(int i=0;i<mbd->mmap_length;i+=sizeof(multiboot_memory_map_t))  {
        multiboot_memory_map_t* mmmt =  (multiboot_memory_map_t*) (0xC0000000 + mbd->mmap_addr + i);

        if(mmmt->type != MULTIBOOT_MEMORY_AVAILABLE || mmmt->addr > 0xFFFFFFFF) {
            continue;
        }

        if(((size_t)mmmt->addr) >= 0x100000 && mmmt->len > mem_pool_len) {
            void* addr = separate_and_pick_larger_three_sections((void*)(size_t)mmmt->addr, (size_t)mmmt->len, 0x100000, 0x100000 + get_kernel_size());
            size_t size = (size_t)mmmt->len - (size_t)addr - (size_t)mmmt->addr;

            if(size > mem_pool_len) {
                mem_pool_start = ((size_t)addr) + 4096;
                // Align the address to page-boundariesanything
                mem_pool_start = ((size_t)mem_pool_start) - (((size_t)mem_pool_start) % 4096);
                mem_pool_len = size;
            }
        }
    }

    mem_pool_len -= mem_pool_len % 4096;

    printf("memory pool is %u bytes long", mem_pool_len, mem_pool_start);
    
    current_page_dir = kernel_page_dir;
    ds_base = (void*)0xC0400000;
    ds_end  = (void*)0xC07FFFFF;
    ds_len  = 0x00000000;
    ds_used = 0x00000000;

    // Allocate 254 pages for the 1GiB - (2*PAGE_SIZE) to complete the kernel
    // area space (these page tables will be static for the remainder of the
    // runtime of the kernel after this function)
    for(int i=0;i<254;i++) {
        void* table = alloc_page((void*)0xC0000000, 0);
        kernel_page_dir[770+i] = ((size_t)table) | 3;
    }

    flush_tlb();
}

void* get_current_pagedir() {
    return current_page_dir;
}

void *kmalloc(size_t size, uint32_t flags) {
    if(size == 0) {
        return NULL;
    }

    if(flags & MALLOC_ALIGNED_4096 && (ds_used % 4096) != 0) {
        ds_used += 4096 - ds_used % 4096;
    }

    ds_used += size;

    while(ds_len < ds_used) {
        if(alloc_page(ds_base + ds_len, 0) == NULL) return NULL;
        ds_len += PAGE_SIZE;
    }

    void* addr = (void*)((size_t)ds_base + ds_used - size);

    if(flags & MALLOC_FILL_ZERO) memset(addr, 0, size);

    return addr;
}

void memset(void *ptr, int val, size_t amount) {
    for(int i=0;i<amount;i++) {
        *(uint8_t*)(ptr+i) = val;
    }
}

void memcpy(void*dest, void*src, size_t num) {
    for(size_t i=0;i<num;i++)
        *(uint8_t*)(dest+i) = *(uint8_t*)(src+i);
}

// Allocate a page and put it at addr, returning the physical address of the
// page
void* alloc_page(void* addr, uint32_t flags) {
    if(((size_t)addr % PAGE_SIZE) != 0) {
        kpanic("Address (0x%08X) is not page-aligned", addr);
    }

    size_t pdindex = (size_t)addr >> 22;
    size_t ptindex = (size_t)addr >> 12 & 0x03FF;

    if(!(current_page_dir[pdindex] & 1)) {
        current_page_dir[pdindex] = (mem_pool_start + mem_pool_used) | 3;
        data_page_table[1023] = (mem_pool_start + mem_pool_used) | 3;
        mem_pool_used += PAGE_SIZE;

        flush_tlb();
    } else {
        data_page_table[1023] = (current_page_dir[pdindex] & ~(0xFFF)) | 3;
        invalidate_page(SKETCH_PAGE);
    }

    *(size_t*)(SKETCH_PAGE + ptindex*4) = (mem_pool_start + mem_pool_used) | 3;
    mem_pool_used += PAGE_SIZE;
    invalidate_page((size_t)addr);

    return (void*)(mem_pool_start + mem_pool_used - PAGE_SIZE);
}

void remove_page(void* addr) {
    return;
}

// Reallocate pages, optionally copying all data between the previous pages and
// the new pages. Flags are specified as PAGE_FLAG_*
void* realloc_pages(void* start, uint32_t pagecount, uint32_t new_pagecount, uint32_t flags) {
    return NULL;
}

void* virt_to_phys(void* addr) {
    size_t pdindex = (size_t)addr >> 22;
    size_t ptindex = (size_t)addr >> 12 & 0x03FF;
    
    size_t *pd = (size_t *)get_current_pagedir();
    if(!(pd[pdindex] & 1)) return NULL;

    // This sets 0xFFC00000 - 0xFFFFFFFF to the page table
    data_page_table[1023] = (pd[pdindex] & ~(0xFFF)) | 3;
    invalidate_page(SKETCH_PAGE);

    size_t* pt = (size_t*)SKETCH_PAGE;

    return (void*)((pt[ptindex] & ~(0xFFF)) + ((size_t)addr&0xFFF));
}

